/* Generated by: ParserGeneratorCC: Do not edit this line. Provider.java Version 1.1 */
/* ParserGeneratorCCOptions:KEEP_LINE_COLUMN=true */
package dev.jorel.fortelangprime.parser;

import java.io.IOException;

/**
 * Abstract interface for reading from a stream.
 * The buffering should be done internally.
 */
public interface Provider extends java.io.Closeable
{
  /**
   * Reads characters into an array
   *
   * @param aDest Destination buffer. May not be <code>null</code>.
   * @param nOfs Offset at which to start storing characters. Must be &ge; 0.
   * @param nLen The maximum possible number of characters to read. Must be &ge; 0.
   * @return The number of characters read, or -1 at the end of the stream
   * @exception IOException if reading fails
   */
  int read (char [] aDest, int nOfs, int nLen) throws IOException;
}
 
/* ParserGeneratorCC - OriginalChecksum=6a0b9a8f0938974600f02a38b56b2242 (do not edit this line) */
