/* Generated By:JavaCC: Do not edit this line. ForteLangPrimeParserConstants.java */
package dev.jorel.fortelangprime.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ForteLangPrimeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPENBRACKET = 1;
  /** RegularExpression Id. */
  int CLOSEBRACKET = 2;
  /** RegularExpression Id. */
  int OPENCBRACE = 3;
  /** RegularExpression Id. */
  int CLOSECBRACE = 4;
  /** RegularExpression Id. */
  int OPENSBRACKET = 5;
  /** RegularExpression Id. */
  int CLOSESBRACKET = 6;
  /** RegularExpression Id. */
  int COLON = 7;
  /** RegularExpression Id. */
  int SEMICOLON = 8;
  /** RegularExpression Id. */
  int ARROW = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int FAT_ARROW = 11;
  /** RegularExpression Id. */
  int DOUBLE_ARROW = 12;
  /** RegularExpression Id. */
  int PLAY_BUTTON = 13;
  /** RegularExpression Id. */
  int GUARD = 14;
  /** RegularExpression Id. */
  int PIPE = 15;
  /** RegularExpression Id. */
  int EQUALS = 16;
  /** RegularExpression Id. */
  int LCHEVRON = 17;
  /** RegularExpression Id. */
  int RCHEVRON = 18;
  /** RegularExpression Id. */
  int PRINTABLE = 19;
  /** RegularExpression Id. */
  int EQUALABLE = 20;
  /** RegularExpression Id. */
  int CONCAT = 21;
  /** RegularExpression Id. */
  int PLUS = 22;
  /** RegularExpression Id. */
  int ROUGHLY_EQUALS = 23;
  /** RegularExpression Id. */
  int TYPE_INT = 24;
  /** RegularExpression Id. */
  int TYPE_BOOL = 25;
  /** RegularExpression Id. */
  int TYPE_STRING = 26;
  /** RegularExpression Id. */
  int TYPE = 27;
  /** RegularExpression Id. */
  int IF = 28;
  /** RegularExpression Id. */
  int THEN = 29;
  /** RegularExpression Id. */
  int ELSE = 30;
  /** RegularExpression Id. */
  int TRUE = 31;
  /** RegularExpression Id. */
  int FALSE = 32;
  /** RegularExpression Id. */
  int PANIC = 33;
  /** RegularExpression Id. */
  int LIBRARY = 34;
  /** RegularExpression Id. */
  int SCRIPT = 35;
  /** RegularExpression Id. */
  int EXPORT = 36;
  /** RegularExpression Id. */
  int IMPORT = 37;
  /** RegularExpression Id. */
  int AS = 38;
  /** RegularExpression Id. */
  int VAR_NAME = 39;
  /** RegularExpression Id. */
  int INT_LITERAL = 40;
  /** RegularExpression Id. */
  int NUMBER = 41;
  /** RegularExpression Id. */
  int STRING = 42;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int InsideMLC = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\";\"",
    "\"->\"",
    "\",\"",
    "\"=>\"",
    "\"->>\"",
    "\"|>\"",
    "\"?:\"",
    "\"|\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"@Printable\"",
    "\"@Equalable\"",
    "\"++\"",
    "\"+\"",
    "\"~=\"",
    "\"Int\"",
    "\"Bool\"",
    "\"String\"",
    "\"type\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"panic\"",
    "\"Library\"",
    "\"Script\"",
    "\"export\"",
    "\"import\"",
    "\"as\"",
    "<VAR_NAME>",
    "<INT_LITERAL>",
    "<NUMBER>",
    "<STRING>",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "\"\\f\"",
    "<token of kind 48>",
    "\"#[\"",
    "\"#[\"",
    "\"]#\"",
    "<token of kind 52>",
  };

}
