/* Generated By:JavaCC: Do not edit this line. ForteLangPrimeConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ForteLangPrimeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPENBRACKET = 1;
  /** RegularExpression Id. */
  int CLOSEBRACKET = 2;
  /** RegularExpression Id. */
  int OPENCBRACE = 3;
  /** RegularExpression Id. */
  int CLOSECBRACE = 4;
  /** RegularExpression Id. */
  int OPENSBRACKET = 5;
  /** RegularExpression Id. */
  int CLOSESBRACKET = 6;
  /** RegularExpression Id. */
  int COLON = 7;
  /** RegularExpression Id. */
  int ARROW = 8;
  /** RegularExpression Id. */
  int FAT_ARROW = 9;
  /** RegularExpression Id. */
  int DOUBLE_ARROW = 10;
  /** RegularExpression Id. */
  int PLAY_BUTTON = 11;
  /** RegularExpression Id. */
  int CONCAT = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int ROUGHLY_EQUALS = 14;
  /** RegularExpression Id. */
  int NUM = 15;
  /** RegularExpression Id. */
  int BOOL = 16;
  /** RegularExpression Id. */
  int STRING = 17;
  /** RegularExpression Id. */
  int MATCH = 18;
  /** RegularExpression Id. */
  int VAR_NAME = 19;
  /** RegularExpression Id. */
  int NUMBER = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\"->\"",
    "\"=>\"",
    "\"->>\"",
    "\"|>\"",
    "\"++\"",
    "\"+\"",
    "\"~=\"",
    "\"Num\"",
    "\"Bool\"",
    "\"String\"",
    "\"match\"",
    "<VAR_NAME>",
    "<NUMBER>",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
  };

}
